# This docker-compose file is only intended for local development.

version: "3"
services:

  db:
    image: library/postgres:11.2
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  queue:
    image: redis:5.0
    command: redis-server --requirepass ${REDIS_PASSWORD?Variable not set}
    env_file:
      - .env

  message-bus:
    image: rabbitmq:3-management
    env_file:
      - .env

  example-api:
    image: semisafe/wiremock:latest
    command: "--root-dir /mocks"
    volumes:
      - ./ci/mocks/example-api:/mocks

  template-service:
    # Run a specific tag of a service image with the command: `TAG=<new-tag> docker-compose up`
    image: '${DOCKER_IMAGE?Variable not set}:${TAG-latest}'
    depends_on:
      - db
      - queue
    ports:
      - 8080:80
    env_file:
      - .env
    environment:
      - SERVER_HOST=http://${DOMAIN?Variable not set}
    volumes:
      - ./app:/app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
        BUILD_IMAGE: dev
    # `start-reload.sh` is provided in the base image, it runs the FastAPI with file-watches in reload mode.
    command: /start-reload.sh

volumes:
  app-db-data:
