name: Dependency Management
description: Checks cached dependencies and installs dependencies if needed

on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{inputs.python_version}}
      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Load installed dependencies from cache
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: poetry-${GITHUB_REF##*/}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies if no cache found
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |
          poetry config --local virtualenvs.in-project true
          poetry install
