name: Create Release within Sentry
on: [release]

jobs:
  create-sentry-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY__GHA_RELEASE_INTEGRATION__RAW }}
          SENTRY_ORG: hingehealth
          SENTRY_PROJECT: ${{ github.event.repository.name }}
        with:
          ignore_missing: true
          ignore_empty: true
